name: tintok
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  firebase_core: ^3.6.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  skeletonizer: ^1.4.2
  get_thumbnail_video: ^0.7.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
