name: tintok
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  firebase_core: ^3.6.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  skeletonizer: ^1.4.2
  get_thumbnail_video: ^0.7.2
  flutter_localizations:
    sdk: flutter

  
  # C'est un package que j'ai créé pour les outils de développement
  flutter_tools_a3studio:
    git:
      url: git@github.com:MaPharma/flutter_tools_a3studio.git
      ref: main
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_translation: ^0.20.0
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
